### ISSUE TITLE
Getting a panic under stress

### ISSUE THREAD

**Issue by jeremyrickard** [census-ecosystem/opencensus-go-exporter-ocagent#13]
👋 

I'm attempting to integrate the oc agent exporter with my application. When I apply a moderate load to the service that I've instrumented with OC and the exporter, I'm reliably getting a panic from the "google.golang.org/api/support/bundler" library:

```
panic: semaphore: bad release

goroutine 6105 [running]:
demo/vendor/golang.org/x/sync/semaphore.(*Weighted).Release(0xc4204e3720, 0xffffffffffffff38)
	/go/src/demo/vendor/golang.org/x/sync/semaphore/semaphore.go:102 +0x1be
demo/vendor/google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1.1(0xc4202040c0, 0x8ba960, 0xc420a43200, 0x97, 0xffffffffffffff38, 0xd)
	/go/src/demo/vendor/google.golang.org/api/support/bundler/bundler.go:268 +0x39
demo/vendor/google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1(0xc4202040c0, 0x8ba960, 0xc420a43200, 0x97, 0xffffffffffffff38, 0xd)
	/go/src/demo/vendor/google.golang.org/api/support/bundler/bundler.go:273 +0xd5
created by demo/vendor/google.golang.org/api/support/bundler.(*Bundler).startFlushLocked
	/go/src/demo/vendor/google.golang.org/api/support/bundler/bundler.go:266 +0x110
```

My demo app is pretty bare bones, but I'm happy to share the file if that would be useful. 

Any tips on how to overcome this would be greatly appreciated.

**Comment by odeke-em** [comment]
Thank you for the report and welcome to ocagent-exporter, @jeremyrickard!

For sure, please share the file as this will be helpful to file a bug with the bundler. If the code is private, please feel free to send it via email.

**Comment by reyang** [comment]
@odeke-em Jeremy and I got a consistent repro with **go1.10.2 windows/amd64**, as well as running in the **iron/go:dev** docker container.
I'll post the repro code here shortly.

**Comment by odeke-em** [comment]
Thank you @reyang! Now am assuming that the agent running locally is a custom agent that receives spans via gRPC right? I will work on this after lunch.

**Comment by reyang** [comment]
@odeke-em, that's right! Thank you :)

**Comment by odeke-em** [comment]
Thank you for the patience @reyang and @jeremyrickard, plus for the repro hint! I made a reproducer in Go and the issue was the usage of `-1` as a "size hint" yet it should have been `1`. I've submitted the reproducer as a regression test and the fix all in #16 PTAL.

**Comment by odeke-em** [comment]
@jeremyrickard @reyang please refresh with `go get -u contrib.go.opencensus.io/exporter/ocagent`

**Comment by reyang** [comment]
@odeke-em, problem solved - just gave it a try and stressed to >10,000 RPS without an issue! Thanks for the quick turnaround 👍

**Comment by jeremyrickard** [comment]
Thanks a lot @odeke-em!!
