### ISSUE TITLE
trace, metrics: add Resource

### ISSUE THREAD

**Issue by songy23** [census-ecosystem/opencensus-go-exporter-ocagent#17]
Currently `Node.Attributes` is an empty map:
https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/00af367e65149ff1f2f4b93bbfbb84fd9297170d/nodeinfo.go#L39

We should add resource type and resource labels to the attribute map, once we have an agreement on https://github.com/census-instrumentation/opencensus-specs/pull/162.

**Comment by odeke-em** [comment]
@songy23 thanks for filing this issue!

So resource specs have since changed. I'll send a PR right now.
