### ISSUE TITLE
Add dependency metadata.

### ISSUE THREAD

**Issue by songy23** [census-ecosystem/opencensus-go-exporter-ocagent#2]
Similar to what we did for opencensus-go-exporter-stackdriver: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/3.

**Comment by odeke-em** [comment]
@songy23 I believe this is what @ramonza has implemented with https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/9. Thank you @ramonza! 

I'll close this issue then. Please feel free to reopen if not fully resolved.
