### ISSUE TITLE
all: remove WithPort in favour of only using the WithAddress option

### ISSUE THREAD

**Issue by rakyll** [census-ecosystem/opencensus-go-exporter-ocagent#22]
Exporter provides two options WithAddress and WithPort.

No need to provide two options because ":port" is a valid address that can translate to "127.0.0.1:port".

**Comment by songy23** [comment]
Not sure if this is the best practice in Go but I think it's nice to have a convenient option to use `localhost` with a custom port. E.g https://github.com/grpc/grpc-java/blob/81da3eb95be37fa0647ce8da2e19de96ab84c600/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L92-L112.

**Comment by rakyll** [comment]
In Go, it is so easy to pass a port as ":port", we often don't provide a port option. I filed this issue from the orthogonality perspective and reduce the number of different ways to achieve the same result.

**Comment by odeke-em** [comment]
Great suggestion @rakyll to remove one of the two. I'd go for removing WithPort, it is inflexible, constrained only to localhost and its types seem subjective as per #21 while WithAddress allows us to dial to whatever host, host:port combination, DNS names etc.
