### ISSUE TITLE
metrics: implement an exporter

### ISSUE THREAD

**Issue by odeke-em** [census-ecosystem/opencensus-go-exporter-ocagent#31]
In lieu of https://github.com/census-instrumentation/opencensus-go/issues/956 which I suspect is going to take a very long time to resolve but also because it is a breaking change to OpenCensus-Go,
it is natural that in order for users to start extracting stats and exporting them to the agent, we provide a metrics exporter.

### Implementation
In order for us to use the current stats exporters from OpenCensus-Go i.e. those that receive view.Data https://godoc.org/go.opencensus.io/stats/view#Exporter
```go
type Exporter interface {
    ExportView(vd *view.Data)
}
```
we'll need to make a translator from [view.Data](https://godoc.org/go.opencensus.io/stats/view#Data) to [metrics.Metric](https://godoc.org/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1#Metric).
The mapping between those two seems straightforward.

The exporter here will firstly implement [view.Exporter](https://godoc.org/go.opencensus.io/stats/view#Exporter) and then whenever OpenCensus-Go's metrics.Exporter is implemented, that'll be a trivial addition which will directly allow this exporter to upload content to the agent.

**Comment by songy23** [comment]
> In lieu of census-instrumentation/opencensus-go#956 which I suspect is going to take a very long time to resolve but also because it is a breaking change to OpenCensus-Go

In Java that was a quite simple change. We simply updated Exporters to consume `Metric` instead of `ViewData` but still keep the `ViewData` API around. In addition, updating the internals of Exporters isn't visible to users, so I don't think there's any breaking changes here. Though maybe it's not the case for Go.

**Comment by odeke-em** [comment]
Alright, I believe with PRs #32 and #34 having been merged, this issue can be closed. There is a complementary PR #35 but that's not a blocker and it is also a simple PR.
