### ISSUE TITLE
stats, metrics: view.SumData should translate to metricspb.Point_SummaryValue

### ISSUE THREAD

**Issue by odeke-em** [census-ecosystem/opencensus-go-exporter-ocagent#36]
Alluded to in a separate PR https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/65/files#r240020411 in which @songy23 reminded me about `SummaryValue`.

I seem to have mistakenly translated `view.SumData` into `metricspb.Point_Int64Value` but really it should be `metricspb.Point_SummaryValue`

**Comment by songy23** [comment]
Apologies if my previous comments caused confusion - SumData should be converted to Int64 or Double. There's a native type `Summary` which needs to be handled separately. See https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/65#discussion_r240061389.
