### ISSUE TITLE
Build failed because of resource dep

### ISSUE THREAD

**Issue by bdymchenkosv** [census-ecosystem/opencensus-go-exporter-ocagent#38]
Commit `060bba92d72213ba66cefc082501aaf9690ab0db` makes build failed: 
```go: finding go.opencensus.io/resource latest
go build go.opencensus.io/resource: no Go files in 
```
I suggest that `go.mod` wasn't updated to the actual state

**Comment by odeke-em** [comment]
Thank you for filing this issue @bdymchenkosv and for the ping @songy23!

OpenCensus-Go hasn't 0.19.0 with the resource packages unfortunately hasn't yet been released
https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/38#issue-389417581
<img width="1108" alt="screen shot 2018-12-10 at 4 50 49 pm" src="https://user-images.githubusercontent.com/4898263/49770987-dcd6df80-fc9b-11e8-9fb7-1575513da219.png">
  
/cc @bogdandrutu to help make that OpenCensus-Go release.

**Comment by odeke-em** [comment]
I've filed https://github.com/census-instrumentation/opencensus-go/issues/998

**Comment by bogdandrutu** [comment]
What do I need to do?

**Comment by bdymchenkosv** [comment]
We can do one of the following: 
1. Revert commit which adds using `resource` package, which is not in stable release `opencensus-go`
2. Update `go.mod` file to use lastest version of `opencensus-go` from master
3. Ask `opencensus-go` to make release `v0.19.1` which adds missing package

**Comment by bdymchenkosv** [comment]
In such case, please add tag `v0.4.1` so `go get -u` will fetch an update

**Comment by songy23** [comment]
Apologies - where should I add the tag? @bdymchenkosv 

I changed version of OC-Go from `v0.18.0` to master and ran `go get`, the result is https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/39.

**Comment by bdymchenkosv** [comment]
I think tag should be added after merging PR to this package

**Comment by songy23** [comment]
Added a new tag v0.4.1 which fixed the dependency issue: https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/releases/tag/v0.4.1.
