### ISSUE TITLE
Referring to go.opencensus.io/exemplar fails

### ISSUE THREAD

**Issue by caghand** [census-ecosystem/opencensus-go-exporter-ocagent#50]
The file [transform_stats_to_metrics.go](https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/7aed492875382edabce5bd833aad08ee8de8d2ad/transform_stats_to_metrics.go) references go.opencensus.io/exemplar, but that file has moved to go.opencensus.io/metric/metricdata with the following commit:
https://github.com/census-instrumentation/opencensus-go/commit/604812a238915a34d8783eb79cedeabd9aca0cc4

**Comment by caghand** [comment]
Just noticed that someone already submitted a PR for this!: #49

**Comment by songy23** [comment]
Fixed with https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/49.
