### ISSUE TITLE
exporter/ocagent/transform_stats_to_metrics.go:257:5: cannot use exmplr.Attachments (type metricdata.Attachments) as type map[string]string in field value

### ISSUE THREAD

**Issue by wuriyanto48** [census-ecosystem/opencensus-go-exporter-ocagent#52]
i got this error when i am trying to build my project using go build
-  go version 1.11
- dependencies might be related
  - github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1
  - go.opencensus.io/metric/metricdata

**Comment by zed-rishabh** [comment]
@wuriyanto48 I am also facing the same issue.
