### ISSUE TITLE
Tag a new version for go.mod update

### ISSUE THREAD

**Issue by jle** [census-ecosystem/opencensus-go-exporter-ocagent#59]
Can a new tag be made for the go.mod update bc69a60230000ba2fe80ce3aba578b8cc6ec7587? We've encountered the problem with `go get -u` from the change to `golang.org/x/lint`.

https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver will need an update as well.

Thank you

**Comment by songy23** [comment]
Done: https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/releases/tag/v0.4.11.

For Stackdriver exporter please use v0.10.0, it already incorporates the `go.mod` updates: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/releases/tag/v0.10.0.

**Comment by jle** [comment]
Thank you!

I think Stackdriver exporter v0.10.0 still depends on some older versions with the problem, https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/v0.10.0/go.mod:

```
	cloud.google.com/go v0.37.1
	contrib.go.opencensus.io/exporter/ocagent v0.4.9
```

**Comment by songy23** [comment]
Got it, I'll update the dependencies in Stackdriver exporter as well.
